### ISSUE TITLE
Generate time.Time from string/date-time

### ISSUE THREAD

**Issue by ghost** [omissis/go-jsonschema#12]
Would it be possible to generate a Go time.Time type from schema string/date-time? Example:
```
    "start_date": {
      "description": "The actual start date",
      "type": "string",
      "format": "date-time"
    }
```
currently creates
```
StartDate string `json:"start_date"`
```
but it should be
```
StartDate time.Time `json:"start_date"`
```

For my use case I do not require validation, so generating the correct type (`time.Time`) would suffice.

**Comment by atombender** [comment]
You can define your schema with a custom type:

```json
"start_date": {
  "description": "The actual start date",
  "type": "string",
  "format": "date-time",
  "goJSONSchema": {
    "type": "time.Time"
  }
}
```

**Comment by ghost** [comment]
That's a nice possibility. Unfortunately, the schema file is not under my control, so I would need to "extend" it as you propose every time it changes. If it's ok for you I could put in a PR for this?

**Comment by ghost** [comment]
Nevermind, wrote a small converter to add 
```
      "goJSONSchema": {
        "type": "time.Time",
        "imports": ["time"],
      }
```

**Comment by atombender** [comment]
Great!
