### ISSUE TITLE
Support for "integer" type

### ISSUE THREAD

**Issue by louis77** [omissis/go-jsonschema#2]
Great that this project was started!

Just started testing and found that type "integer" is not supported. However, specs define two numeric types: "number" and "integer": https://json-schema.org/understanding-json-schema/reference/numeric.html

Would you consider implementing integer as a supported type? If so, I'd be happy to draft a PR.

**Comment by atombender** [comment]
Hm, I didn't realize that JSON Schema had `integer`. It's not in the core spec, only in the validation spec. I assume that this is become JSON Schema doesn't consider it an "instance type". A PR would be appreciated.
