### ISSUE TITLE
Master tests broken since "YAML commits"

### ISSUE THREAD

**Issue by jmaeso** [omissis/go-jsonschema#20]
From [0c601dda828c010901ca01e9cfcb8cf7649f90c3 commit](https://github.com/atombender/go-jsonschema/commit/0c601dda828c010901ca01e9cfcb8cf7649f90c3), which introduces support for generating the code from a YAML file (at least that's what I understood), the tests are broken since the types now get generated with a trailing `-Json` suffix.

I tried to update the tests at first in order to unblock open PRs, but actually debugging the issue made me realize that the types should not contain the input mechanism as part of their name.
[Here](https://github.com/atombender/go-jsonschema/commit/0c601dda828c010901ca01e9cfcb8cf7649f90c3#diff-3eff1f64609d574a15dea5b30ab0e3ae1ccf7977891b8ed3c019fd5a2349a094R233) (I think) is the place where the bug was introduced.

After this debugging session, my conclusion is that the YAML feature is not very well documented, justified, and decoupled from JSON implementation (probably because the YAML addition was not planned since the beginning).

**Comment by atombender** [comment]
Thanks. The problem was simply that the tests had not been updated. This tool is being used in a larger project that has solid integration tests relating to JSON schemas, so the failing tests weren't being run very often, which of course was a mistake.

The YAML support is perfectly fine, IMHO.
