### ISSUE TITLE
mark a new release as latest?

### ISSUE THREAD

**Issue by codefromthecrypt** [omissis/go-jsonschema#22]
Hi, I'm happy with what you've done and would love to have no questions about including this in a project. Would you mind tagging a new release or setting the last tag as latest? It seems a cheap confidence builder.

**Comment by atombender** [comment]
Will do.

**Comment by atombender** [comment]
There's a new tag, but Travis is broken and isn't building the release yet. Working on a fix.

**Comment by atombender** [comment]
Release [here](https://github.com/atombender/go-jsonschema/releases/tag/v0.9.0).

**Comment by codefromthecrypt** [comment]
works great. thanks!
