### ISSUE TITLE
Feature request: string pattern validation

### ISSUE THREAD

**Issue by antontornqvist** [omissis/go-jsonschema#239]
Currently the code generated does not validate string patterns. Would be nice to have, any plans to add it?

**Comment by omissis** [comment]
hey! uhm it's not in the plans for now, no. I want to close the last PR, do a round of cleanups on the issues, and then probably kick-off a rewrite :)

**Comment by antontornqvist** [comment]
Ok, I can open a PR for adding this functionality if you accept contributions?

**Comment by omissis** [comment]
oh if you're willing, sure! that would be great :)

**Comment by antontornqvist** [comment]
There was some other validation missing that I added in the PR as well. `(exclusive)maximum` and `(exclusive)minimum` for numeric types and `uniqueItems` for arrays :)

**Comment by omissis** [comment]
closed by #264
