### ISSUE TITLE
Mark a new release as latest?

### ISSUE THREAD

**Issue by hunterwerlla** [omissis/go-jsonschema#49]
Very similar to https://github.com/atombender/go-jsonschema/issues/22, I'd like to consume the fix from https://github.com/atombender/go-jsonschema/issues/32, but I would like to have it tied to an actual release.

Thanks!

**Comment by omissis** [comment]
Hi @hunterwerlla, I was given the ownership of this repository and I have started planning the milestone v0.10.0. Hopefully I will be able to push it out this month! :)

**Comment by omissis** [comment]
v0.10.0 released, closing this issue.
