### ISSUE TITLE
Explore goplayground's validator

### ISSUE THREAD

**Issue by omissis** [omissis/go-jsonschema#61]
Validation is an important topic for this library, as proven by some of the PRs received by the community, such as #38 and #10.

I would like to explore the possibility to integrate goplayground's validation library as a mean to offer more complete support for json schema validation.

**Comment by KhanMechAI** [comment]
Having used that library, it would make sense +1

**Comment by omissis** [comment]
Validation will be re-evaluated in the future trying a different approach, so I am deprecating this issue.
