### ISSUE TITLE
Feature request: support configuring generated struct tags

### ISSUE THREAD

**Issue by codeboten** [omissis/go-jsonschema#79]
Currently the generated code always sets a struct tag for json, yaml, and mapstructure. See:

https://github.com/omissis/go-jsonschema/blob/172061399cba4a93f95ac5cf3b3935daa147e966/pkg/generator/generate.go#L807-L811

It would be great if it was possible to pass in a configuration option to specify which of these to set.

**Comment by omissis** [comment]
Hi @codeboten, thanks for raising this issue and for contributing the PR! Question: do those unused, extra tags cause issues in downstream code, or is this change done for "cosmetic" purposes only?

**Comment by codeboten** [comment]
@omissis the request came from this comment https://github.com/open-telemetry/opentelemetry-collector/pull/7679#discussion_r1195493280. The rest of the code for the configuration for the collector only contains `mapstructure` struct tags, so i think this is mostly for consistency

**Comment by omissis** [comment]
I see, thanks. I'll ask on that PR and I will take a look over the weekend

**Comment by codeboten** [comment]
@omissis any thoughts on whether the PR for this feature can get merged?

**Comment by omissis** [comment]
@codeboten yeah I asked on the pr some clarifications, and I'm ok with offloading some maintenance off them to have it here, even though I feel the command interface is becoming a bit bloated. I'll see to review this PR as soon as possible. Thanks!
