### ISSUE TITLE
minItems wrong implementation

### ISSUE THREAD

**Issue by giorgionocera** [omissis/go-jsonschema#86]
Hi everyone, first of all, thank you for your work. 
I'm using your tool and up to yesterday, I never had to do with the `minItems` property in an array.
Yesterday I had, I had some problems you can follow here:
https://github.com/cosmos/chain-registry/issues/2352

After some reasoning with the reviewer on that repo, I better investigated the issue. I'll report here the results as I did on the other repo (https://github.com/cosmos/chain-registry/pull/2353).

> Since it was unclear to me from the [documentation](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.3.3), I tried a [validator online](https://www.jsonschemavalidator.net/) and I understood that the `minItems` property only requires at least an "image" **if the "image" field is defined**.

The code generated through `go-jsonschema` instead, makes the field required. So If there is no image, (`minItems = 1`) the object is not validated. For this reason, it seems to be conceptually wrong.

What do you think?
Thank you for your time!

**Comment by omissis** [comment]
Hey @giorgionocera thanks for reporting the issue, I will look into it soon

**Comment by omissis** [comment]
HI @giorgionocera, I have just merged pr #122 by @nick-jones that should be fixing the issue you highlighted. If that's the case, can you confirm so I can close this issue? thanks!

**Comment by giorgionocera** [comment]
Hi @omissis , yeah I tried the new code. 
It works!
Thank you and @nick-jones for your work 🚀 
You can close the issue, thank you again.

**Comment by omissis** [comment]
awesome! thanks 🙏
