### ISSUE TITLE
Handling of `required` properties in objects

### ISSUE THREAD

**Issue by Henkoglobin** [omissis/go-jsonschema#97]
According to [§6.5.3 of the JSON Schema Validation spec](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-required), `required` properties need merely be _present_ in the input JSON, they are not required to be non-`null`. 

As such, the validation generated by go-jsonschema is too strict, as it checks for presence (which is correct) but also validates that the value is not `nil`.

For example, with the following schema:

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "RequiredObjectPropertiesTest",
    "properties": {
        "requiredNillableProp": {
            "type": [
                "string",
                "null"
            ]
        }
    },
    "required": [
        "requiredNillableProp"
    ]
}
```

This input is valid: 

```json
{
  "requiredNillableProp": null	
}
```

But an empty JSON object `{}` is not.

As such, properties marked as `required` should generate _without_ `omitempty` and should be checked for presence, but not for non-nil.

**Comment by jerbob92** [comment]
I have fixed this in my own fork for now: https://github.com/klippa-app/go-jsonschema/blob/feature/required-fix/pkg/generator/validator.go#L38

I did not add the actual null check there because I have no need for it.
